feat: knobs with nullable values
ookami-kb/storybook_flutter pull request #74
Opened 2022-03-01 20:32 UTC by Kirpal

## Description

This PR adds the ability for knobs to have a nullable value. This is useful to see what a widget looks like in its default state. To use a nullable knob, the public API is very similar to the existing API, except you use an extra nullable prefix when accessing knobs, ie `context.knobs.nullable.boolean` rather than `context.knobs.boolean`. The rest of the public API remains the same.

For the UI, knobs now have a leading switch to toggle whether or not they're null. If they aren't nullable, this switch is shown but disabled.

https://user-images.githubusercontent.com/18384371/156241768-554c1293-60c8-4954-bf38-25ab464edbc4.mov

2022-03-06 18:54 UTC, ookami-kb requested changes
Looks really good! Just a couple of small points from me.

2022-03-06 18:54 UTC, ookami-kb commented on packages/storybook_flutter/lib/src/knobs/knobs_builder.dart
> +    bool enabled = false,
I would say that it should rather be enabled by default (for all the knobs).

2022-03-06 18:54 UTC, ookami-kb commented on packages/storybook_flutter/lib/src/knobs/knob_list_tile.dart
> +  Widget build(BuildContext context) => SwitchListTile(
Let's rather hide the switch if knob is not nullable, instead of just disabling it – it would look cleaner.

2022-03-09 08:36 UTC, ookami-kb commented
@Kirpal UI tests are failing, can you please take a look? Keep in mind that they are running on Linux instance, so there can be differences if you launch them on another OS.

You can download the results of golden tests as an artifact of CI run. Most probably, they shouldn't change at all as an outcome of this PR.

2022-03-09 12:54 UTC, Kirpal commented
Yes, they are failing because of differences in font rendering. How do you usually do it, are you on a Linux machine? I'm on a Mac and don't have a machine to generate them on.

2022-03-09 12:59 UTC, ookami-kb commented
I usually download CI build artifact (it generates diffs and full files there) and just replace my local files with the generated ones and do another commit. Not an ideal flow, but I don't know any better solution for now 🤷

2022-03-09 17:14 UTC, ookami-kb approved these changes

2022-03-09 17:16 UTC, merged

2022-03-11 16:19 UTC, Kirpal commented
@ookami-kb any way we could get a new release with these changes?

2022-03-11 16:20 UTC, ookami-kb commented
@Kirpal sure, will prepare a release today.